"""Generate a source-file manifest and Python symbol index using only the stdlib."""

import ast
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / ".agents" / "codemap.md"
SOURCE_DIRS = {"golf_league", "tests", "templates", "static", "migrations", "docs", "scripts"}
ROOT_FILES = {"AGENTS.md", "Makefile", "pyproject.toml", "Dockerfile", "compose.yml",
              "docker-compose.yml", "alembic.ini", "uv.lock"}


def generate() -> None:
    """Index present tracked and nonignored source files without copying their contents."""
    inventory = subprocess.check_output(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
        cwd=ROOT,
    ).decode().split("\0")
    paths = sorted({name for name in inventory if name and (ROOT / name).is_file()
                    and (name in ROOT_FILES or Path(name).parts[0] in SOURCE_DIRS)
                    and not any(part.startswith(".") for part in Path(name).parts)})
    lines = ["# Golf League source map", "",
             "Generated by `python scripts/generate_codemap.py`.", "",
             "This is a file manifest and Python AST symbol index, not a call graph.",
             "Private data, ignored files, and source contents are excluded.", "",
             "## Files and Python symbols", ""]
    for name in paths:
        lines.append(f"### `{name}`")
        lines.append("")
        if name.endswith(".py"):
            tree = ast.parse((ROOT / name).read_text(), filename=name)
            for item in tree.body:
                if isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                    kind = "class" if isinstance(item, ast.ClassDef) else "function"
                    lines.append(f"- {kind} `{item.name}` (line {item.lineno})")
                    if isinstance(item, ast.ClassDef):
                        for method in item.body:
                            if isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef)):
                                lines.append(f"  - method `{method.name}` (line {method.lineno})")
        lines.append("")
    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text("\n".join(lines))


if __name__ == "__main__":
    generate()
